development:
  adapter: postgresql
  encoding: unicode
  database: properdeed-api
  pool: 5
  username: serge
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: properdeed-api-test
  pool: 5
  username: serge
  password: